### ISSUE TITLE
Replace HelveticaNeue font with free one

### ISSUE THREAD

**Issue by naffiq** [samdark/yiifeed-redesign#1]
I was working on markup and noticed that the font used in sketches is HelveticaNeue which costs a lot.

Any opportunity on switching to a free font?

**Comment by samdark** [comment]
Let's try Roboto or PTSans.

**Comment by naffiq** [comment]
Here are some screenshots

## Roboto
![Roboto](http://pics.rocketfirm.com/galym/News_-_YiiFeed_-_Google_Chrome_2017-05-03_02.29.08.png)

## PT Sans
![PTSans](http://pics.rocketfirm.com/galym/News_-_YiiFeed_-_Google_Chrome_2017-05-03_02.26.42.png)

Personally liked Roboto more, content seems more readable

**Comment by samdark** [comment]
Agree.
